// Database of Crop Details (Structured for Translation)
// keys correspond to the 'crops' keys in translations.js

export const cropDetails = {
    // --- CEREALS & GRAINS ---
    "wheat": { category: "grain", season: "Rabi", soil: "loamy", water: "moderate", temp: "10-25°C" },
    "paddy": { category: "grain", season: "Kharif", soil: "clay", water: "high", temp: "25-35°C" },
    "rice": { category: "grain", season: "Kharif", soil: "clay", water: "high", temp: "25-35°C" },
    "maize": { category: "grain", season: "Kharif", soil: "loamy", water: "moderate", temp: "21-27°C" },
    "barley": { category: "grain", season: "Rabi", soil: "sandy_loam", water: "low", temp: "12-25°C" },
    "bajra": { category: "grain", season: "Kharif", soil: "sandy", water: "low", temp: "25-35°C" },
    "jowar": { category: "grain", season: "Kharif", soil: "sandy_loam", water: "low", temp: "26-33°C" },
    "ragi": { category: "grain", season: "Kharif", soil: "loamy", water: "moderate", temp: "20-30°C" },
    "millet": { category: "grain", season: "Kharif", soil: "sandy", water: "low", temp: "25-30°C" },
    "buckwheat": { category: "grain", season: "Kharif", soil: "acidic", water: "moderate", temp: "15-25°C" },
  
    // --- PULSES (DAL) ---
    "gram": { category: "pulse", season: "Rabi", soil: "loamy", water: "low", temp: "20-25°C" },
    "chickpea": { category: "pulse", season: "Rabi", soil: "loamy", water: "low", temp: "20-25°C" },
    "arhar": { category: "pulse", season: "Kharif", soil: "loamy", water: "moderate", temp: "25-30°C" },
    "tur": { category: "pulse", season: "Kharif", soil: "loamy", water: "moderate", temp: "25-30°C" },
    "soyabean": { category: "pulse", season: "Kharif", soil: "loamy", water: "moderate", temp: "25-30°C" },
    "rajmash": { category: "pulse", season: "Rabi", soil: "loamy", water: "moderate", temp: "15-25°C" },
    "peas": { category: "pulse", season: "Rabi", soil: "loamy", water: "moderate", temp: "10-20°C" },
    "black gram": { category: "pulse", season: "Kharif", soil: "loamy", water: "moderate", temp: "25-35°C" },
    "green gram": { category: "pulse", season: "Kharif", soil: "loamy", water: "moderate", temp: "25-35°C" },
  
    // --- VEGETABLES ---
    "potato": { category: "vegetable", season: "Rabi", soil: "sandy_loam", water: "moderate", temp: "15-20°C" },
    "onion": { category: "vegetable", season: "Rabi", soil: "loamy", water: "moderate", temp: "15-25°C" },
    "tomato": { category: "vegetable", season: "Rabi", soil: "loamy", water: "moderate", temp: "20-25°C" },
    "cauliflower": { category: "vegetable", season: "Rabi", soil: "loamy", water: "moderate", temp: "15-20°C" },
    "spinach": { category: "vegetable", season: "Rabi", soil: "loamy", water: "moderate", temp: "10-20°C" },
    "carrot": { category: "vegetable", season: "Rabi", soil: "sandy_loam", water: "moderate", temp: "15-20°C" },
    "okra": { category: "vegetable", season: "Kharif", soil: "loamy", water: "moderate", temp: "25-35°C" },
    "brinjal": { category: "vegetable", season: "Kharif", soil: "loamy", water: "moderate", temp: "25-30°C" },
    "garlic": { category: "vegetable", season: "Rabi", soil: "loamy", water: "moderate", temp: "12-25°C" },
    "ginger": { category: "vegetable", season: "Kharif", soil: "loamy", water: "high", temp: "20-30°C" },
    "chilli": { category: "vegetable", season: "Kharif", soil: "sandy_loam", water: "moderate", temp: "20-30°C" },
    "cucumber": { category: "vegetable", season: "Zaid", soil: "sandy_loam", water: "moderate", temp: "25-35°C" },
    "pumpkin": { category: "vegetable", season: "Zaid", soil: "loamy", water: "moderate", temp: "20-30°C" },
    "turnip": { category: "vegetable", season: "Rabi", soil: "loamy", water: "moderate", temp: "10-15°C" },
    "sweet potato": { category: "vegetable", season: "Kharif", soil: "sandy_loam", water: "moderate", temp: "20-30°C" },
    "drumstick": { category: "vegetable", season: "Perennial", soil: "sandy_loam", water: "low", temp: "25-35°C" },
    "tapioca": { category: "vegetable", season: "Kharif", soil: "loamy", water: "moderate", temp: "25-30°C" },
  
    // --- FRUITS ---
    "mango": { category: "fruit", season: "Summer", soil: "loamy", water: "moderate", temp: "25-40°C" },
    "banana": { category: "fruit", season: "All Year", soil: "loamy", water: "high", temp: "25-30°C" },
    "apple": { category: "fruit", season: "Winter", soil: "loamy", water: "moderate", temp: "5-20°C" },
    "kinnow": { category: "fruit", season: "Winter", soil: "loamy", water: "moderate", temp: "10-25°C" },
    "orange": { category: "fruit", season: "Winter", soil: "loamy", water: "moderate", temp: "10-25°C" },
    "grapes": { category: "fruit", season: "Summer", soil: "sandy_loam", water: "moderate", temp: "15-40°C" },
    "pomegranate": { category: "fruit", season: "All Year", soil: "sandy_loam", water: "low", temp: "25-35°C" },
    "papaya": { category: "fruit", season: "All Year", soil: "loamy", water: "high", temp: "25-30°C" },
    "pineapple": { category: "fruit", season: "All Year", soil: "sandy_loam", water: "high", temp: "20-30°C" },
    "guava": { category: "fruit", season: "Winter", soil: "loamy", water: "moderate", temp: "15-30°C" },
    "litchi": { category: "fruit", season: "Summer", soil: "loamy", water: "high", temp: "25-35°C" },
    "peach": { category: "fruit", season: "Summer", soil: "loamy", water: "moderate", temp: "10-25°C" },
    "plum": { category: "fruit", season: "Summer", soil: "loamy", water: "moderate", temp: "10-25°C" },
    "apricot": { category: "fruit", season: "Summer", soil: "loamy", water: "moderate", temp: "10-25°C" },
    "cherry": { category: "fruit", season: "Summer", soil: "loamy", water: "moderate", temp: "10-20°C" },
    "lemon": { category: "fruit", season: "All Year", soil: "loamy", water: "moderate", temp: "20-30°C" },
    "jackfruit": { category: "fruit", season: "Summer", soil: "loamy", water: "moderate", temp: "25-35°C" },
    "kiwi": { category: "fruit", season: "Winter", soil: "loamy", water: "moderate", temp: "5-20°C" },
    "passion fruit": { category: "fruit", season: "Summer", soil: "loamy", water: "moderate", temp: "20-30°C" },
    "breadfruit": { category: "fruit", season: "All Year", soil: "loamy", water: "high", temp: "25-35°C" },
    "sapota": { category: "fruit", season: "Winter", soil: "loamy", water: "moderate", temp: "20-30°C" },
    "walnut": { category: "fruit", season: "Autumn", soil: "loamy", water: "moderate", temp: "5-20°C" },
    "almond": { category: "fruit", season: "Autumn", soil: "loamy", water: "moderate", temp: "15-25°C" },
  
    // --- CASH CROPS & SPICES ---
    "cotton": { category: "commercial", season: "Kharif", soil: "black", water: "moderate", temp: "25-35°C" },
    "sugarcane": { category: "commercial", season: "All Year", soil: "loamy", water: "high", temp: "20-40°C" },
    "tea": { category: "commercial", season: "All Year", soil: "acidic", water: "high", temp: "15-25°C" },
    "coffee": { category: "commercial", season: "All Year", soil: "loamy", water: "high", temp: "20-30°C" },
    "mustard": { category: "commercial", season: "Rabi", soil: "loamy", water: "moderate", temp: "10-25°C" },
    "sunflower": { category: "commercial", season: "All Year", soil: "loamy", water: "moderate", temp: "20-30°C" },
    "groundnut": { category: "commercial", season: "Kharif", soil: "sandy_loam", water: "moderate", temp: "25-30°C" },
    "turmeric": { category: "commercial", season: "Kharif", soil: "loamy", water: "high", temp: "20-30°C" },
    "jute": { category: "commercial", season: "Kharif", soil: "clay", water: "high", temp: "25-35°C" },
    "tobacco": { category: "commercial", season: "Rabi", soil: "loamy", water: "moderate", temp: "20-30°C" },
    "rubber": { category: "commercial", season: "All Year", soil: "loamy", water: "high", temp: "25-35°C" },
    "coconut": { category: "commercial", season: "All Year", soil: "sandy", water: "moderate", temp: "25-30°C" },
    "arecanut": { category: "commercial", season: "All Year", soil: "laterite", water: "high", temp: "15-35°C" },
    "cardamom": { category: "commercial", season: "All Year", soil: "loamy", water: "high", temp: "10-35°C" },
    "pepper": { category: "commercial", season: "All Year", soil: "loamy", water: "high", temp: "10-40°C" },
    "saffron": { category: "commercial", season: "Autumn", soil: "loamy", water: "moderate", temp: "5-15°C" },
    "cashewnut": { category: "commercial", season: "Summer", soil: "sandy", water: "low", temp: "20-35°C" },
    "coriander": { category: "commercial", season: "Rabi", soil: "loamy", water: "moderate", temp: "15-25°C" },
    "cumin": { category: "commercial", season: "Rabi", soil: "sandy", water: "low", temp: "20-30°C" },
    "isabgol": { category: "commercial", season: "Rabi", soil: "sandy_loam", water: "low", temp: "15-25°C" },
    "clove": { category: "commercial", season: "All Year", soil: "loamy", water: "high", temp: "20-30°C" },
    "nutmeg": { category: "commercial", season: "All Year", soil: "clay_loam", water: "high", temp: "20-30°C" },
    "cinnamon": { category: "commercial", season: "All Year", soil: "sandy", water: "high", temp: "20-30°C" },
    "sesame": { category: "commercial", season: "Kharif", soil: "sandy_loam", water: "low", temp: "25-30°C" },
    "guar": { category: "commercial", season: "Kharif", soil: "sandy", water: "low", temp: "25-35°C" },
    "castor": { category: "commercial", season: "Kharif", soil: "sandy_loam", water: "low", temp: "20-25°C" },
    "rose": { category: "commercial", season: "All Year", soil: "loamy", water: "moderate", temp: "15-30°C" }
  };